export const GET_BREEDS_LIST = 'GET_BREEDS_LIST';
export const GET_BREEDS_LIST_SUCCESS = 'GET_BREEDS_LIST_SUCCESS';
export const GET_BREEDS_LIST_FAILURE = 'GET_BREEDS_LIST_FAILURE';

// dog by breed actions

export const GET_DOG_BY_BREED = 'GET_DOG_BY_BREEDS';
export const GET_DOG_BY_BREED_SUCCESS = 'GET_DOG_BY_BREED_SUCCESS';
export const GET_DOG_BY_BREED_FAILURE = 'GET_DOG_BY_BREED_FAILURE';

// random dog image actions

export const GET_RANDOM_IMAGE = 'GET_RANDOM_IMAGE';
export const GET_RANDOM_IMAGE_SUCCESS = 'GET_RANDOM_IMAGE_SUCCESS';
export const GET_RANDOM_IMAGE_FAILURE = 'GET_RANDOM_IMAGE_FAILURE';

// browse breed list actions

export const BROWSE_BREED_IMAGE = 'BROWSE_BREED_IMAGE';
export const BROWSE_BREED_IMAGE_SUCCESS = 'BROWSE_BREED_IMAGE_SUCCESS';
export const BROWSE_BREED_IMAGE_FAILURE = 'BROWSE_BREED_IMAGE_FAILURE';